
--SELECT * FROM CUSTOMER;
--SELECT * FROM LINE;
--SELECT * FROM APPOINTMENTS;
--SELECT * FROM SALON;
--SELECT * FROM BEAUTICIAN;
--SELECT * FROM CERTIFICATIONS;
--SELECT * FROM REWARD_POINTS;
--SELECT * FROM MEMBERSHIP_TYPE;
--SELECT * FROM INVOICE;
--SELECT * FROM SALON_SERVICES;


------01--------
SELECT C.CUST_LNAME, C.CUST_FNAME, I.INVOICE_NUM, SUM(L.LINE_UNITS*L.LINE_PRICE) AS TOTAL_AMOUNT
FROM CUSTOMER AS C
INNER JOIN INVOICE AS I ON C.CUST_ID = I.CUST_ID
INNER JOIN LINE AS L ON I.INVOICE_NUM = L.INVOICE_NUM
GROUP BY C.CUST_LNAME, C.CUST_FNAME, I.INVOICE_NUM
ORDER BY TOTAL_AMOUNT ASC;


------02--------
SELECT S.SALON_ID,  SUM(CASE WHEN APP_TYPE = 'B' THEN 1 ELSE 0 END) AS Count_BOOKED,
SUM(CASE WHEN APP_TYPE = 'W' THEN 1 ELSE 0 END) AS Count_WALKINs
FROM SALON AS S INNER JOIN APPOINTMENTS AS A ON S.SALON_ID = A.SALON_ID
WHERE SALON_AREACODE = '48326' OR SALON_AREACODE = '48084'
GROUP BY S.SALON_ID;

------03-------
SELECT B.BEAUT_LNAME AS 'BEAUTICIAN_LAST_NAME', B.BEAUT_FNAME AS BEAUTICIAN_FIRST_NAME,
M.BEAUT_LNAME AS 'MANAGER_LAST_NAME', M.BEAUT_FNAME AS 'MANAGER_FIRST_NAME'
FROM BEAUTICIAN AS B
INNER JOIN
BEAUTICIAN M ON B.BEAUT_MGR = M.BEAUT_ID
ORDER BY B.BEAUT_LNAME ASC;

------04-------
SELECT TOP 1
B.BEAUT_ID, B.BEAUT_LNAME, B.BEAUT_FNAME, COUNT(R.REWARD_ID) AS COUNT_REWARD
FROM BEAUTICIAN AS B INNER JOIN REWARD_POINTS AS R 
ON B.BEAUT_ID = R.BEAUT_ID
GROUP BY  B.BEAUT_ID, B.BEAUT_LNAME, B.BEAUT_FNAME
ORDER BY COUNT_REWARD DESC;

------05-------
SELECT TOP 3 S.SALON_ID, COUNT(A.CUST_ID) AS 'NUM_CUSTOMERS'
FROM SALON S INNER JOIN APPOINTMENTS AS A 
ON S.SALON_ID = A.SALON_ID
GROUP BY S.SALON_ID
ORDER BY NUM_CUSTOMERS DESC;

------06-------
SELECT M.MT_NAME,COUNT(C.CUST_ID) AS 'NUM.OF MEMEBERS'
FROM MEMBERSHIP_TYPE AS M INNER JOIN CUSTOMER AS C
ON M.MT_ID = C.MT_ID
GROUP BY M.MT_NAME
ORDER BY 'NUM.OF MEMEBERS' DESC;


------07-------
SELECT DISTINCT C.CUST_LNAME, C.CUST_FNAME, L.SERVICE_ID, L.LINE_PRICE
FROM CUSTOMER AS C INNER JOIN INVOICE AS I
ON C.CUST_ID = I.CUST_ID INNER JOIN LINE AS L
ON I.INVOICE_NUM = L.INVOICE_NUM
WHERE L.LINE_PRICE = (SELECT MAX(LINE_PRICE) FROM LINE)
ORDER BY C.CUST_LNAME DESC;

------08-------
SELECT P.P_CODE,P.P_NAME,I.INVOICE_DATE, SUM(L.LINE_UNITS) AS 'TOTAL_UNITS_SOLD', SUM(L.LINE_UNITS * L.LINE_PRICE) AS 'TOTAL_SALES'
FROM PRODUCT AS P INNER JOIN LINE AS L
ON P.P_CODE = L.P_CODE
INNER JOIN INVOICE AS I ON L.INVOICE_NUM = I.INVOICE_NUM
WHERE I.SALON_ID = '114'
GROUP BY P.P_CODE,P.P_NAME,I.INVOICE_DATE
ORDER BY 'TOTAL_SALES' DESC;

------09-------
SELECT S.SALON_ID, AVG(B.BEAUT_PAYRATE) AS AVG_SALARY
FROM SALON AS S INNER JOIN BEAUTICIAN AS B ON S.SALON_ID = B.SALON_ID
GROUP BY S.SALON_ID
ORDER BY AVG_SALARY DESC;

------10-------
SELECT C.CUST_LNAME,C.CUST_FNAME,I.CUST_ID,I.INVOICE_NUM, CC.CC_PAYMENT_AMT, CR.CC_NUM, CR.ISSUER
FROM CUSTOMER AS C INNER JOIN INVOICE AS I ON C.CUST_ID = I.CUST_ID
INNER JOIN CC_PAYMENT AS CC ON I.INVOICE_NUM = CC.INVOICE_NUM
INNER JOIN CREDITCARD AS CR ON CC.CC_NUM = CR.CC_NUM
ORDER BY C.CUST_LNAME ASC;

------11-------
SELECT C.CUST_LNAME,C.CUST_FNAME,I.CUST_ID,I.INVOICE_NUM, CHK.CHECK_AMT, CH.CHECK_NUM, 
CHK.CHECK_ACC_NUM, CHK.CHECK_ROUTING_NUM
FROM CUSTOMER AS C INNER JOIN INVOICE AS I ON C.CUST_ID = I.CUST_ID
INNER JOIN CHECK_PAYMENT AS CH ON I.INVOICE_NUM = CH.INVOICE_NUM
INNER JOIN CHECKS AS CHK ON CHK.CHECK_NUM = CH.CHECK_NUM
ORDER BY C.CUST_LNAME ASC;

------12-------
SELECT *
FROM CUSTOMER AS C 
LEFT JOIN MEMBERSHIP_TYPE AS M
ON C.MT_ID = M.MT_ID;

------13(A)-------
SELECT *
FROM MEMBERSHIP_TYPE
LEFT JOIN PROMOTIONS
ON MEMBERSHIP_TYPE.MT_ID = PROMOTIONS.MT_ID;

------13(B)-------
SELECT * FROM MEMBERSHIP_TYPE WHERE MT_ID NOT IN (SELECT MT_ID FROM PROMOTIONS);

------14------
SELECT C.CUST_ID,CP.INVOICE_NUM,CP.CASH_RECEIPT_NUM,CP.CASH_PAYMENT_AMT
FROM CASH AS C INNER JOIN CASH_PAYMENT AS CP 
ON C.CASH_RECEIPT_NUM=CP.CASH_RECEIPT_NUM
WHERE CP.CASH_PAYMENT_DATE BETWEEN '2022-01-01' AND '2022-12-31'
ORDER BY 1;

------15------
SELECT C.CUST_ID,C.CUST_LNAME,C.CUST_FNAME,S.SERVICE_NAME,S.SERVICE_PRICE
FROM CUSTOMER AS C INNER JOIN SALON_SERVICES AS S 
ON C.CUST_ID=S.CUST_ID
WHERE S.SERVICE_PRICE > 20;






